#[theme]
#base="dark"
#primaryColor="#F63366"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
#font="sans serif"

[theme]
base="light"
primaryColor="#a9a9a9"
backgroundColor="#ffffff"
textColor="#6495ed"
font="serif"
